### PR TITLE
feat: allows users specifying a message when saving

### LINKED ISSUE #31: feat: Allow different commit message
## New feature
Something like pmz save --message "<my message>" would add custom commit message.
## Current behaviour
By default there is no option to change commit message
Default message `updating your zettelkasten` could be used if `--message` is not specified.

### PR DESCRIPTION
**Pull request by gsilvapt**
Closes #31.

@AugustasV not sure how comfortable you are with testing this but this is the feature you requested. If you are unable to test it, I can merge this and we can test using the resulting binary.

Thanks a lot for your contribution.

### CODE REVIEW

**Comment by AugustasV** [comment]
I was using terratest for some projects, but not sure about that

**Comment by gsilvapt** [comment]
Seems a bit overkill for this. 

I need to read more on how to release and install alpha/beta releases - sorry. For the time being, to try this build you would have to pull from this branch, run `go build -o bin/pmz` and run the commands with this binary `bin/pmz ...`.

**Comment by AugustasV** [comment]
Hi @gsilvapt  Tried to do that, I run command without anything I get that
```
augustasv@augustasv-ProBook:~/Documents/zet$ ~/Documents/pmz/bin/pmz 
panic: "message" shorthand is more than one ASCII character

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00013e500, 0xc0001b8e60)
        /home/augustasv/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:864 +0x4bf
github.com/spf13/pflag.(*FlagSet).VarPF(0xdfc800, {0xa7a780, 0xc0001b0ac0}, {0x9b39c6, 0x1}, {0x9b515e, 0x7}, {0x9d29cc, 0x3d})
        /home/augustasv/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x151
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /home/augustasv/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVarP(0x1, 0xc00013e200, {0x9b39c6, 0xc00013e200}, {0x9b515e, 0xc00013e200}, {0x9c0689, 0x9e9508}, {0x9d29cc, 0x3d})
        /home/augustasv/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string.go:42 +0x6e
github.com/spf13/pflag.(*FlagSet).StringP(...)
        /home/augustasv/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string.go:67
github.com/gsilvapt/pmz/cmd.init.2()
        /home/augustasv/Documents/pmz/cmd/save.go:86 +0xa
```
Actually I can't run any command, all the time getting this error.

**Comment by gsilvapt** [comment]
Sorry for that. Fixed it and it worked now. Tested locally. Going to merge the changes and you can install the latest version.
Thanks!

**Pull request merged**
